apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80       # Internal service port
    targetPort: 80 # Nginx container port
    nodePort: 30080 # External port (must be between 30000-32767)

